### ISSUE TITLE
reblend 2 sets of frames sequentially

### ISSUE THREAD

**Issue by imalmg** [alt-key-project/comfyui-dream-video-batches#2]
I really apricate the work you've done with these nodes but I was wondering if there is a way I can use them to recombine 2 batches of images that come from the same original video. 
Currently I have a video that has numbered frames 1-300, and I was able to easily split them into odd (1,3,5,7...)frames and even (2,4,6,8...)frames. But every tool that combines them either requires a manual switch, or replacement, or appends them at the end. 
I want to be able to use the frame count or active frame from each batch in a comparison which then drives a Boolean that switches between source folders.

**Comment by moreAImore** [comment]
Did you guys made workflows with nodes fromthis custom node? I would like to see one if you could share?
@imalmg

**Comment by alt-key-project** [comment]
Sorry for the ridiculously long wait for a reply - I have been completely out of ComfyUI for a while. As far as I understand your request, this sounds like something that would be more of a frame by frame processing workflow (such as Deforum) than a batch video workflow (such as AnimateDiff). I so, it is possible you could use the "Big Image Switch" in the "Dream Project Animation".
