### ISSUE TITLE
Where are the workflows?

### ISSUE THREAD

**Issue by lunatico67** [alt-key-project/comfyui-dream-video-batches#5]
Hi
Thanks for the node, it looks like a very creative and attractive contribution.
I have installed it and there is no workflow in its folder

**Comment by Hakim3i** [comment]
Same unusable

**Comment by moreAImore** [comment]
Did you guys made workflows with nodes fromthis custom node? I would like to see one if you could share?
@lunatico67  @Hakim3i

**Comment by alt-key-project** [comment]
Sorry for the ridiculously long wait - a few examples have been added.

**Comment by moreAImore** [comment]
> Sorry for the ridiculously long wait - a few examples have been added.

Hero!
