### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by carlobs** [alt-key-project/comfyui-dream-video-batches#9]
Hi, launching the "pip install -r requirementes.txt" i receive the error:

![immagine](https://github.com/user-attachments/assets/6a2c5739-0ce0-4b29-949f-42de765bdac9)

also with the embedded phyton
![immagine](https://github.com/user-attachments/assets/37532086-e9b0-4a84-bedd-e8e97190e49a)

**Comment by alt-key-project** [comment]
Thanks for the bug report! Should be resolved now.
